//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoicetable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoicetable()
        {
            this.Ordertables = new HashSet<Ordertable>();
        }
    
        public int inid { get; set; }
        public Nullable<int> infkuser { get; set; }
        public Nullable<System.DateTime> indate { get; set; }
        public Nullable<double> intotalbill { get; set; }
    
        public virtual ProductTable ProductTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordertable> Ordertables { get; set; }
    }
}
